### ISSUE TITLE
[ALL][EPIC] Architecture

### ISSUE THREAD

**Issue by djey47** [djey47/cool-updown-nxt#1]
Switch to a nodeJS backend and a proper UI framework on client side.

So that the API could be invoked with different clients (own web UI, magic mirror module, mobile app....)

## Planned features/stories:

- Preparing
  - [x]  Rename current repo to cool-updown-legacy
  - [x] Create new mono repo (cool-updown-nxt)
  - [x] Migrate tasks and features to new repo
- Migrate current 'services' to JSON REST API
  - [x] Persist state to disk to handle services shutdown or restarts
  - [x] Implement polling to backend and API will just query the internal state  
  - [ ] DEBUG mode as env variable?
  - [x] Persisted statistics to track uptimes
- Create a front-end with Vite + TS + React
  - [ ] PWA
  - [x] Introduce React Query / polling to API (or web sockets?)
  - [ ] Stats view (charts...)
- Create a magic mirror 2 module (new github repository)
  - [ ] make portal module embedding some special UI version of the above front-end
- Create Alexa skill to get device status or perform actions  
 
- Documentation update
  - [x] GH repo update (description etc)
